language: perl
perl:
  - "5.30"
install:
    - cpanm -v --installdeps --notest .
script: "perl Makefile.PL && make test"
os:
  - linux
  - freebsd
notifications:
  email:
    on_success: always
    on_failure: always
